on:
  workflow_call:
    inputs:
      id:
        required: false
        default: ${{ github.job }}
        type: string

jobs:
  called-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.id }}"
